openapi: 3.0.3

info:
  title: Ping API
  version: 1.0.0

paths:
  /:
    post:
      operationId: pingBody
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ping'
      responses:
        200:
          description: Returns value of ping
          content:
            application/json:
              schema:
                type: object
                properties:
                  pong:
                    type: string

components:
  schemas:
    ping:
      type: object
      properties:
        ping:
          type: string
      required:
        - ping
